export type Lang = 'en' | 'mr';

export const UI = {
  en: {
    back:           'Back',
    stockCheck:     'Stock Check',
    dailyKitchen:   'Daily Kitchen',
    enterPin:       'Enter your PIN to continue',
    hi:             'Hi,',
    checkDate:      'Check date',
    date:           'Date',
    filled:         'Filled',
    morningIn:      'Morning IN',
    closing:        'Closing',
    save:           'Save',
    saving:         'Saving…',
    verifying:      'Verifying…',
    saved:          'Saved!',
    done:           'Done',
    logOther:       (shift: string) => `Log ${shift}`,
    saveBtn:        (label: string, n: number) => `Save ${label} (${n})`,
    saveBtnEmpty:   (label: string) => `Save ${label}`,
    minLevel:       'min level — verify count',
    last:           (qty: number, unit: string, date: string) => `Last: ${qty} ${unit} · ${date}`,
    items:          'items',
    fillOne:        'Fill at least one quantity',
    invalidPin:     'Invalid PIN',
  },
  mr: {
    back:           'मागे',
    stockCheck:     'साठा तपासणी',
    dailyKitchen:   'दैनंदिन स्वयंपाकघर',
    enterPin:       'पुढे जाण्यासाठी PIN टाका',
    hi:             'नमस्कार,',
    checkDate:      'तपासणी तारीख',
    date:           'तारीख',
    filled:         'भरलेले',
    morningIn:      'सकाळचे',
    closing:        'रात्रीचे',
    save:           'जतन करा',
    saving:         'जतन होत आहे…',
    verifying:      'तपासत आहे…',
    saved:          'जतन केले!',
    done:           'झाले',
    logOther:       (shift: string) => `${shift} नोंद करा`,
    saveBtn:        (label: string, n: number) => `${label} जतन करा (${n})`,
    saveBtnEmpty:   (label: string) => `${label} जतन करा`,
    minLevel:       'किमान पातळी — मोजणी तपासा',
    last:           (qty: number, unit: string, date: string) => `मागील: ${qty} ${unit} · ${date}`,
    items:          'वस्तू',
    fillOne:        'किमान एक प्रमाण भरा',
    invalidPin:     'चुकीचा PIN',
  },
} as const;

/** Fallback Marathi item names — used when name_mr column is not yet in DB */
export const MR_ITEMS: Record<string, string> = {
  // Daily kitchen
  'Shev pav Bun':          'शेव पाव बन',
  'Burger Bun':            'बर्गर बन',
  'Bun Maska':             'बन मस्का',
  'Pizza base':            'पिझ्झा बेस',
  'Sandwich Bread':        'सँडविच ब्रेड',
  'Khichiya Papad':        'खिचिया पापड',
  'Surti Coco':            'सुरती कोको',
  'Onion':                 'कांदा',
  'Tomato':                'टोमॅटो',
  'Cucumber':              'काकडी',
  'Lemon':                 'लिंबू',
  'Capsicum':              'सिमला मिरची',
  'Bell pepper - Red':     'लाल भोपळी मिरची',
  'Bell pepper - Yellow':  'पिवळी भोपळी मिरची',
  'Kairi':                 'कैरी',
  'Roasted Makhana':       'भाजलेले मखाणे',
  'Raw Makhana':           'कच्चे मखाणे',
  'Milk':                  'दूध',
  'Coriander':             'कोथिंबीर',
  'Paneer':                'पनीर',
  'Maggi':                 'मॅगी',
  'Fresh Cream':           'फ्रेश क्रीम',
  'Potato':                'बटाटा',
  // Weekly stock
  'imli chutney':          'चिंच चटणी',
  'mayo':                  'मेयो',
  'tomato ketchup':        'टोमॅटो केचप',
  'chipotle':              'चिपोटले',
  'tandoori':              'तंदूरी सॉस',
  'white pasta sauce':     'पांढरी पास्ता सॉस',
  'pizza pasta sauce Reg': 'पास्ता सॉस (रेग्युलर)',
  'pizza pasta sauce JAIN':'पास्ता सॉस (जैन)',
  'cheese dressing':       'चीज ड्रेसिंग',
  'Cheese Blend':          'चीज ब्लेंड',
  'Sunflower oil 1L':      'सूर्यफूल तेल',
  'Snapin cheese garlic masala': 'चीज गार्लिक मसाला',
  'peri peri big pack':    'पेरी पेरी (मोठे)',
  'Snapin peri peri pouches': 'पेरी पेरी पाउच',
  'Maggi masala 60pc bag': 'मॅगी मसाला',
  'Chat Masala':           'चाट मसाला',
  'Salt':                  'मीठ',
  'Coffee sachets':        'कॉफी सॅशे',
  'Sugar sachets':         'साखर सॅशे',
  'Ketchup sachets':       'केचप सॅशे',
  'Oregano sachets':       'ओरेगॅनो सॅशे',
  'Chilli Flakes sachets': 'चिली फ्लेक्स सॅशे',
  'Sugar':                 'साखर',
  'elaichi':               'वेलची',
  'Tea Masala':            'चहा मसाला',
  'Tata Agni 1.5kg':       'टाटा अग्नी',
  'Society Tea 1kg':       'सोसायटी चहा',
  'bru 200g':              'ब्रू कॉफी',
  'continental 200g':      'कॉन्टिनेंटल कॉफी',
  'coco premix':           'कोको प्रिमिक्स',
  'Kairi Panna Premix':    'कैरी पन्हा प्रिमिक्स',
  'Sabja':                 'सब्जा',
  'Chocolate powder':      'चॉकलेट पावडर',
  'Dark compound slab':    'डार्क कंपाउंड',
  'Cocoa powder':          'कोको पावडर',
  'yellow shev':           'पिवळे शेव',
  'orange shev':           'नारंगी शेव',
  'Chana dal':             'चणा डाळ',
  'kurkure':               'कुरकुरे',
  'lays - Cream n onion':  'लेज (क्रीम ओनियन)',
  'lays - Magic masala':   'लेज (मॅजिक मसाला)',
  'nachos':                'नाचोस',
  'maggi':                 'मॅगी',
  'Khicha papad':          'खिचिया पापड',
  'Khakra':                'खाखरा',
  'Potato Chips':          'बटाटा चिप्स',
  'Pasta':                 'पास्ता',
  'Raw Shengdana':         'कच्चे शेंगदाणे',
  'Straw small':           'स्ट्रॉ (लहान)',
  'Straw big':             'स्ट्रॉ (मोठे)',
  'Container & lids small':'डबा व झाकण (लहान)',
  'Container & lids big':  'डबा व झाकण (मोठे)',
  'Beverage container':    'पेय डबा',
  'Stirrer':               'स्टिरर',
  'Shev pav parcel box':   'शेव पाव बॉक्स',
  'Cups big':              'कप (मोठे)',
  'Bags small':            'पिशवी (लहान)',
  'Bags big':              'पिशवी (मोठी)',
  'Pizza Boxes':           'पिझ्झा बॉक्स',
  'Aloo tikki Patty':      'आलू टिक्की पॅटी',
  'Veggie patty':          'व्हेज पॅटी',
  'Sweet corn 1kg':        'स्वीट कॉर्न',
  'Diced cheese blend 1kg':'चीज ब्लेंड (तुकडे)',
  'Fries 2.5kg':           'फ्राईज',
  'Vanilla Icecream':      'व्हॅनिला आइसक्रीम',
  'Cheese block 1kg':      'चीज ब्लॉक',
  'Butter 500g':           'बटर',
  'Water 500ml':           'पाणी (500ml)',
  'Soda':                  'सोडा',
  'Water 1L':              'पाणी (1L)',
};

/** Resolve display name for an item given current language */
export function itemName(name: string, name_mr: string | null | undefined, lang: Lang): string {
  if (lang !== 'mr') return name;
  return name_mr ?? MR_ITEMS[name] ?? name;
}

export function getLang(): Lang {
  if (typeof window === 'undefined') return 'en';
  return (localStorage.getItem('lang') as Lang) ?? 'en';
}

export function setLang(l: Lang) {
  localStorage.setItem('lang', l);
}
